export enum UserActionType {
	USER_AUTHENTICATE = 'USER_AUTHENTICATE',
	LOGIN_USER_SUCCSESS = 'LOGIN_USER_SUCCSESS',
	LOGIN_USER_ERROR = 'LOGIN_USER_ERROR',
	LOGIN_USER = 'LOGIN_USER',
	LOGOUT_USER = 'LOGOUT_USER',
	REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
	REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
	REGISTER_USER = 'REGISTER_USER',
	WISHLIST_TOGGLE = 'WISHLIST_TOGGLE',
	WISHLIST_ADD = 'WISHLIST_ADD',
	CART_ADD_PRODUCT = 'CART_ADD_PRODUCT',
	CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT',
	CART_PRODUCT_INCREASE = 'CART_PRODUCT_INCREASE',
	CART_PRODUCT_DECREASE = 'CART_PRODUCT_DECREASE',
	CALCULATE_CART_TOTAL = 'CALCULATE_CART_TOTAL',
}

export enum CartActionType {
	CART_ADD_PRODUCT = 'CART_ADD_PRODUCT',
	CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT',
	CART_PRODUCT_INCREASE = 'CART_PRODUCT_INCREASE',
	CART_PRODUCT_DECREASE = 'CART_PRODUCT_DECREASE',
	CALCULATE_CART_TOTAL = 'CALCULATE_CART_TOTAL',
	CART_ADD = 'CART_ADD',
	CART_REMOVE = 'CART_REMOVE',
	CART_CLEAR = 'CART_CLEAR',
	CHANGE_COUNT = 'CHANGE_COUNT',
}

export enum OrderActionType {
	ORDER_ADD = 'ORDER_ADD',
	ORDER_CLEAR = 'ORDER_CLEAR',
	ORDER_ADD_PAYMENT = 'ORDER_ADD_PAYMENT',
	ORDER_ADD_DELIVERY = 'ORDER_ADD_DELIVERY',
	ORDER_ADD_PRODUCTS = 'ORDER_ADD_PRODUCTS',
	ORDER_ADD_USER = 'ORDER_ADD_USER',
	NEW_ORDER = 'NEW_ORDER',
	NEW_USER = 'NEW_USER',
}

export enum SearchActionType {
	SEARCH = 'SEARCH',
}
